import { Dancing_Script } from "next/font/google";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const dancingFont= Dancing_Script({
  variable: "--font-Dancing_Script",
  subsets: ["latin"],
  weight: '700'
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={dancingFont.variable}>
      <body>
        {children}
      </body>
    </html>
  );
}
